/// Ahead-of-time JTD code generation.
///
/// Walks `schemas/**/<version>.jtd.json` and emits, per schema, one JavaScript
/// validator for the host/MJS boundary and one Rust validator compiled into
/// the evaluator. Each generated module exports a single `validate`.
///
/// Output is a build artifact: gitignored, never hand-edited. Editing it
/// instead of its schema is a defect. See `schemas/README.md`.
import { readdir, readFile, mkdir, writeFile, rm } from "node:fs/promises";
import { execFile } from "node:child_process";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

const run = promisify(execFile);
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const schemaRoot = join(root, "schemas");
const jsOut = join(root, "tools", "generated");
const rsOut = join(root, "evaluator", "src", "generated");

/// `schemas/fs/artifact/1.0.0.jtd.json` -> `agent-dsl://schemas/fs/artifact/1.0.0`
function schemaUri(absolutePath) {
  const rel = relative(schemaRoot, absolutePath).split(sep).join("/");
  return `agent-dsl://schemas/${rel.replace(/\.jtd\.json$/, "")}`;
}

/// `schemas/fs/artifact/1.0.0.jtd.json` -> `fs_artifact_1_0_0`
function moduleName(absolutePath) {
  return relative(schemaRoot, absolutePath)
    .replace(/\.jtd\.json$/, "")
    .split(sep)
    .join("_")
    .replace(/[.-]/g, "_");
}

async function findSchemas(dir) {
  const found = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) found.push(...(await findSchemas(full)));
    else if (entry.name.endsWith(".jtd.json")) found.push(full);
  }
  return found.sort();
}

async function generate(target, schemaPath) {
  const source = await readFile(schemaPath, "utf8");
  try {
    const { stdout } = await run("jtd-codegen", ["--target", target, schemaPath]);
    return stdout;
  } catch (cause) {
    throw new Error(
      `jtd-codegen --target ${target} failed for ${relative(root, schemaPath)}: ` +
        `${cause.stderr || cause.message}\nschema was:\n${source}`,
    );
  }
}

const schemas = await findSchemas(schemaRoot);
if (schemas.length === 0) throw new Error(`no *.jtd.json found under ${schemaRoot}`);

await rm(jsOut, { recursive: true, force: true });
await rm(rsOut, { recursive: true, force: true });
await mkdir(jsOut, { recursive: true });
await mkdir(rsOut, { recursive: true });

const registry = [];
for (const schemaPath of schemas) {
  const name = moduleName(schemaPath);
  const uri = schemaUri(schemaPath);

  await writeFile(join(jsOut, `${name}.mjs`), await generate("js", schemaPath));

  const rust = await generate("rust", schemaPath);
  await writeFile(join(rsOut, `${name}.rs`), rust);

  registry.push({ name, uri });
}

// JavaScript registry: schema URI -> validate function.
const jsRegistry = [
  "/// Generated by tools/codegen.mjs. Do not edit.",
  ...registry.map((r) => `import { validate as ${r.name} } from "./${r.name}.mjs";`),
  "",
  "export const VALIDATORS = new Map([",
  ...registry.map((r) => `  [${JSON.stringify(r.uri)}, ${r.name}],`),
  "]);",
  "",
  "/// Validate `value` against `uri`. Returns an array of human-readable",
  "/// problems, empty when the value conforms. An unknown URI is itself a",
  "/// problem: a boundary that names a schema nobody generated is a defect.",
  "export function validateAgainst(uri, value) {",
  "  const validator = VALIDATORS.get(uri);",
  "  if (!validator) return [`schema ${uri} is not registered; run npm run codegen`];",
  "  return validator(value).map(",
  "    (e) => `${e.instancePath || '(root)'} does not satisfy ${uri}${e.schemaPath}`,",
  "  );",
  "}",
  "",
].join("\n");
await writeFile(join(jsOut, "index.mjs"), jsRegistry);

// Rust registry: same mapping, exhaustive match over a closed set.
const rsRegistry = [
  "// Generated by tools/codegen.mjs. Do not edit.",
  "// Warnings are silenced at this boundary so that generated code cannot mask",
  "// a real warning in hand-written modules.",
  "#![allow(unused_variables, non_snake_case, clippy::all)]",
  "use serde_json::Value;",
  "",
  ...registry.map((r) => `pub mod ${r.name};`),
  "",
  "/// Validate `value` against `uri`, returning messages that name the",
  "/// offending path and the schema it failed. An unregistered URI is an",
  "/// error rather than a silent pass.",
  "pub fn validate_against(uri: &str, value: &Value) -> Result<(), Vec<String>> {",
  "    let problems: Vec<(String, String)> = match uri {",
  ...registry.map((r) => `        ${JSON.stringify(r.uri)} => ${r.name}::validate(value),`),
  "        other => {",
  "            return Err(vec![format!(",
  '                "schema {other} is not registered; run npm run codegen"',
  "            )])",
  "        }",
  "    };",
  "    if problems.is_empty() {",
  "        return Ok(());",
  "    }",
  "    Err(problems",
  "        .into_iter()",
  "        .map(|(instance_path, schema_path)| {",
  "            let at = if instance_path.is_empty() { \"(root)\" } else { &instance_path };",
  "            format!(\"{at} does not satisfy {uri}{schema_path}\")",
  "        })",
  "        .collect())",
  "}",
  "",
].join("\n");
await writeFile(join(rsOut, "mod.rs"), rsRegistry);

process.stdout.write(`${registry.length} schemas -> ${relative(root, jsOut)}, ${relative(root, rsOut)}\n`);
